CREATE TABLE USERS(
	ID VARCHAR2(8) PRIMARY KEY,
	PASSWORD VARCHAR2(8),
	NAME VARCHAR2(20),
	ROLE VARCHAR2(5)
);

CREATE TABLE BOARD(
	SEQ NUMBER(5) PRIMARY KEY,
	TITLE VARCHAR2(200),
	WRITER VARCHAR2(20),
	CONTENT VARCHAR2(2000),
	REGDATE DATE DEFAULT CURRENT_DATE,
	CNT NUMBER(5) DEFAULT 0
);

INSERT INTO USERS VALUES('admin', 'test123', '서현', 'Admin');
INSERT INTO USERS VALUES('guest', 'test123', '방문자', 'User');

INSERT INTO BOARD(SEQ, TITLE, WRITER, CONTENT) 
VALUES((SELECT NVL(MAX(SEQ), 0) + 1 FROM BOARD), '가입인사', '관리자', '잘 부탁드립니다....');


